import pyttsx3
from lib import ParseDicts

engine = pyttsx3.init()
engine.say(
    "Я протокольный дроид Линг 01. Назовите мне слово, и я расскажу всё о нём")
engine.runAndWait()
wordi = input("")
engine.say("Согласно словарю Даля:")
engine.runAndWait()
engine.say(ParseDicts.Parse1(wordi, "https://diclist.ru/slovar/dalya"))
engine.runAndWait()
engine.say("Согласно словарю Ожегова:")
engine.runAndWait()
engine.say(ParseDicts.Parse1(wordi, "https://diclist.ru/slovar/ozhegova"))
engine.runAndWait()
engine.say("Согласно словарю Ушакова:")
engine.runAndWait()
engine.say(ParseDicts.Parse1(wordi, "https://diclist.ru/slovar/ushakova"))
engine.runAndWait()
engine.say("Согласно словарю Ефремовой:")
engine.runAndWait()
engine.say(ParseDicts.Parse1(wordi, "https://diclist.ru/slovar/efremovoy"))
engine.runAndWait()
engine.say("Синонимы этого слова:")
engine.runAndWait()
engine.say(ParseDicts.Parse2(wordi, "https://sinonim.org/s"))
engine.runAndWait()
engine.say("Антонимы этого слова:")
engine.runAndWait()
engine.say(ParseDicts.Parse2(wordi, "https://sinonim.org/a"))
engine.runAndWait()
engine.say("Этимология этого слова:")
engine.runAndWait()
engine.say(ParseDicts.Etimology(wordi))
engine.runAndWait()
